### ISSUE TITLE
Failed to fetch paginated query response and no cache available.

### ISSUE THREAD

**Issue by Shinzoushein** [RatScanner/RatScanner#747]
**Error**
Failed to fetch paginated query response and no cache available.
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Failed to fetch paginated query response and no cache available.)
 ---> System.Exception: Failed to fetch paginated query response and no cache available.
   at RatScanner.TarkovDevAPI.QueuePaginatedRequest[T](String baseQueryKey, Func`3 queryBuilder, Int64 ttl)
   at RatScanner.TarkovDevAPI.InitializeCache()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at RatScanner.RatScannerMain..ctor()
   at RatScanner.RatScannerMain.get_Instance()
   at RatScanner.View.BlazorUI.<>c.<.ctor>b__11_0(IServiceProvider s)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRun
```
<details>
<summary>Log</summary>

```
[05:16:35.6774848] > [Info]  ----- RatScanner 3.9.1 -----
[05:16:35.6804974] > [Info]  Screen Info: 3440x1440 at 100%
[05:16:35.6805117] > [Info]  Initializing TarkovDev API...
[05:16:35.6806939] > [Info]  Attempting to load API cache from offline storage...
[05:16:38.1077005] > [Info]  Loaded 4809 items from offline cache for: "items_En_Regular"
[05:16:38.1465441] > [Info]  Loaded 26 items from offline cache for: "hideout_En_Regular"
[05:16:38.1604137] > [Info]  Loaded 14 items from offline cache for: "maps_En_Regular"
[05:16:38.1605324] > [Warning] Offline cache status - Items: True, Tasks: False, Hideout: True, Maps: True
[05:16:38.1605407] > [Warning] No complete offline cache available, fetching from network...
[05:16:38.1870408] > [Info]  Fetching batch at offset 0 for: "maps_En_Regular"
[05:16:38.1870574] > [Info]  Fetching batch at offset 0 for: "hideout_En_Regular"
[05:16:38.1876225] > [Info]  Fetching batch at offset 0 for: "items_En_Regular"
[05:16:38.1876528] > [Info]  Fetching batch at offset 0 for: "tasks_En_Regular"
[05:16:38.3429603] > [Warning] Failed paginated request for: "tasks_En_Regular".
[05:16:38.3505889] > System.Exception: Tarkov.dev API request failed. Forbidden
   at RatScanner.TarkovDevAPI.Get(String query)
   at RatScanner.TarkovDevAPI.QueuePaginatedRequest[T](String baseQueryKey, Func`3 queryBuilder, Int64 ttl)
[05:16:38.4584210] > [Info]  Fetched 14 items at offset 0 for: "maps_En_Regular"
[05:16:38.4739703] > [Info]  Completed paginated fetch in 309ms: 14 total items for "maps_En_Regular"
[05:16:38.5394039] > [Info]  Fetched 26 items at offset 0 for: "hideout_En_Regular"
[05:16:38.7590047] > [Info]  Completed paginated fetch in 594ms: 26 total items for "hideout_En_Regular"
[05:16:38.8378759] > [Info]  Fetched 1000 items at offset 0 for: "items_En_Regular"
[05:16:38.8384242] > [Info]  Fetching batch at offset 1000 for: "items_En_Regular"
[05:16:39.2419166] > [Info]  Fetched 1000 items at offset 1000 for: "items_En_Regular"
[05:16:39.2424442] > [Info]  Fetching batch at offset 2000 for: "items_En_Regular"
[05:16:39.6735741] > [Info]  Fetched 1000 items at offset 2000 for: "items_En_Regular"
[05:16:39.6740495] > [Info]  Fetching batch at offset 3000 for: "items_En_Regular"
[05:16:39.9934751] > [Info]  Fetched 1000 items at offset 3000 for: "items_En_Regular"
[05:16:39.9939482] > [Info]  Fetching batch at offset 4000 for: "items_En_Regular"
[05:16:40.2646048] > [Info]  Fetched 809 items at offset 4000 for: "items_En_Regular"
[05:16:42.8085757] > [Info]  Completed paginated fetch in 4644ms: 4809 total items for "items_En_Regular"
[05:16:42.8155526] > [Error] Failed to fetch paginated query response and no cache available.
 -------------------- 
 System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AggregateException: One or more errors occurred. (Failed to fetch paginated query response and no cache available.)
 ---> System.Exception: Failed to fetch p
```
</details>

**Comment by holyfirexx** [comment]
Same here, haven't been able to use rat scanner since 3.9.1

**Comment by snfergy** [comment]
> As a dirty workaround for now, you can copy this [cache](https://cdn.discordapp.com/attachments/1447164357980192888/1447241201894822011/cache.zip?ex=693adc66&is=69398ae6&hm=c8dd26f66705f8be1d7ea9764cbae320242370c624161f6a6d1650a256966f57&) to `C:\Users\User\AppData\Local\Temp\RatScanner\Cache`

Can you upload this to another file hoster? The link expired.
I'm experiencing this issue right now as well.

**Comment by Blightbuster** [comment]
[cache.zip](https://github.com/user-attachments/files/24262900/cache.zip)

> > As a dirty workaround for now, you can copy this [cache](https://cdn.discordapp.com/attachments/1447164357980192888/1447241201894822011/cache.zip?ex=693adc66&is=69398ae6&hm=c8dd26f66705f8be1d7ea9764cbae320242370c624161f6a6d1650a256966f57&) to `C:\Users\User\AppData\Local\Temp\RatScanner\Cache`
> 
> Can you upload this to another file hoster? The link expired. I'm experiencing this issue right now as well.

**Comment by Blightbuster** [comment]
It should be fixed now with version 3.9.2 unfortunately the error occurs before the update check is done so you'll have to download the new version yourself.

**Comment by magnusmc2512** [comment]
I'm still getting this error, even after cache seeding. And yes I'm on the latest version with supposed fix 3.9.2. I've tried running admin, running older versions etc. Still same error...

**Comment by DysektAI** [comment]
Reopening as the canonical thread for the cold-start / no-offline-cache pagination failure (`Failed to fetch paginated query response and no cache available.`).

This was previously closed as fixed in 3.9.2, but it is still reproducing — see the comment below and the steady stream of duplicate reports through July 2026. Consolidating the open duplicates here.

**Workaround** (until the fetch succeeds over the network): seed the cache by placing `cache.zip` contents into `%LocalAppData%\Temp\RatScanner\Cache` so RatScanner can start from the offline cache instead of requiring a fresh paginated fetch.
**Fix attempt:** [v3.9.3 release](https://github.com/tarkovtracker-org/RatScanner/releases/tag/v3.9.3) (addresses the pagination error).

Root-cause hypothesis: tarkov.dev API throttling/availability during the cold-start paginated fetch when no complete offline cache exists.

Stack trace for reference:
```
System.Exception: Failed to fetch paginated query response and no cache available.
   at RatScanner.TarkovDevAPI.QueuePaginatedRequest[T](...)
   at RatScanner.TarkovDevAPI.InitializeCache()
   at RatScanner.RatScannerMain..ctor()
```

If you were pointed here from a closed duplicate, please add your log/repro details to this thread.

**Comment by DysektAI** [comment]
### Duplicate cleanup

#767 was closed as a duplicate of this issue (same TarkovDev paginated query / cache failure class). This issue is kept as the better-documented report.

**Comment by Still-Here-0** [comment]
I have the same problem here, I am running RatScanner on windows 10 with a 3440x1440 display. Cache does not load from TarkovDev, it doesn't even open I just get a crash. When I try to load cache from @Blightbuster the app opens but I can not scan itens, does it log anything after I press the scan button? Here is my logs:

```
[00:53:43.9600850] > [Info]  ----- RatScanner 3.9.3 -----
[00:53:43.9614787] > [Info]  Screen Info: 3440x1440 at 100%
[00:53:43.9614827] > [Info]  Initializing TarkovDev API...
[00:53:43.9615808] > [Info]  Attempting to load API cache from offline storage...
[00:53:44.9566581] > [Info]  Loaded 4797 items from offline cache for: "items_En_Regular"
[00:53:45.2618188] > [Info]  Loaded 497 items from offline cache for: "tasks_En_Regular"
[00:53:45.2809510] > [Info]  Loaded 26 items from offline cache for: "hideout_En_Regular"
[00:53:45.2861146] > [Info]  Loaded 15 items from offline cache for: "maps_En_Regular"
[00:53:45.2861258] > [Info]  All API caches loaded from offline storage
[00:53:45.2862629] > [Info]  Offline cache loaded and fresh, skipping background refresh.
[00:53:45.2866593] > [Info]  Initializing tarkov tracker database
[00:53:45.2867242] > [Info]  Initializing hotkey manager...
[00:53:45.2895270] > [Info]  UI Ready!
[00:53:45.2895360] > [Info]  Initializing RatEye...
[00:53:46.3163624] > [Info]  Checking for updates...
[00:53:46.3173954] > [Info]  Loading resource "RSClientVersion"...
[00:53:46.6918681] > [Info]  Loading TarkovTracker data...
[00:53:46.6918861] > [Info]  Loading TarkovTracker...
[00:53:47.5356785] > [Info]  Setting up timer routines...
[00:53:47.5357013] > [Info]  Enabling hotkeys...
[00:53:47.5357392] > [Info]  Ready!
```

**Comment by DysektAI** [comment]
# Quick Update
### I am testing a `v4.x.x Beta`, it fixes and addresses this and many other issues.

- Its a Work In Progress still likely has other issues that will be addressed and fixed as I make more updates to it so expect changes.
- It will be migrated over to the RatScanner/RatScanner repo once stable fully, until then this is the best option to avoid accidentally pushing unfinished work to everyone else that is unstable.
**(Read the release details as being a beta is does come with some risks that can't be accounted for)**

**You can find the beta here: https://github.com/tarkovtracker-org/RatScanner/releases/tag/v4.0.0-beta**
*It should auto update when more updates are released, but if not ill post an update*

**Comment by Blightbuster** [comment]
Fixed in 3.10.0
